version: 2
updates:
  - package-ecosystem: pip
    directory: "/src"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
  - package-ecosystem: npm
    directory: "/src/web"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1