import {
    File, ChartLine, FileReport, ExternalLink,
    ChartInfographic, Versions, ArrowRight,
    Home, Package, ApiApp, WorldDownload,
    Api, FileDiff, CheckupList, ReportAnalytics,
    Folder, ShieldCheck,
    ShieldX, ShieldOff,
    Code, Affiliate, Book,
    Upload, Hierarchy, Database,
    Elevator, Search, Books,
    ArrowUp, ArrowLeft, ChevronLeft, ChevronRight
} from '@vicons/tabler'
import { Icon } from '@vicons/utils'

export {
    Affiliate as CallIcon,
    Database as DataIcon,
    ShieldCheck as VerifiedIcon,
    ShieldX as UnverifiedIcon,
    Hierarchy as MemberIcon,
    Search as SearchIcon,
    ShieldOff as NoverifyIcon,
    Folder as DataDirectoryIcon,
    ExternalLink as LinkIcon,
    ChartLine as TrendIcon,
    ChartInfographic as CountIcon,
    File as FileIcon,
    Home as HomeIcon,
    Versions as VersionIcon,
    FileReport as LogIcon,
    Books as ProjectIcon,
    ApiApp as RootIcon,
    ArrowRight as GoIcon,
    Icon,
    ChevronLeft as PrevIcon,
    ChevronRight as SuccIcon,
    WorldDownload as DistributionIcon,
    Api as DescriptionIcon,
    FileDiff as DifferenceIcon,
    Package as PackageIcon,
    WorldDownload as PreprocessIcon,
    Api as ExtractIcon,
    FileDiff as DiffIcon,
    CheckupList as EvaluateIcon,
    ReportAnalytics as ReportIcon,
    Code as CodeIcon,
    Book as ViewIcon,
    ArrowUp as ParentIcon,
    Folder as ApiLevelIcon,
    Upload as UploadIcon,
    Elevator as InheritanceIcon
}