import {
    File as FileIcon, ChartLine as TrendIcon, FileReport as LogIcon, ExternalLink as LinkIcon,
    Database as CountIcon, Versions as VersionIcon, Tools as PipelineIcon, ArrowRight as GoIcon,
    Home as HomeIcon, Package as ReleaseIcon, BrandPython as RootIcon, WorldDownload as PreprocessIcon,
    Api as ExtractIcon, FileDiff as DiffIcon, CheckupList as EvaluateIcon, ReportAnalytics as ReportIcon, 
    List as BatchIcon, ListCheck as BatchIndexIcon, Folder as DataDirectoryIcon, ShieldCheck as VerifiedIcon,
    ShieldX as UnverifiedIcon, ShieldOff as NoverifyIcon,
    Code as CodeIcon, PhoneCall as CallIcon,
} from '@vicons/tabler'
import { Icon } from '@vicons/utils'

export {
    CallIcon,
    VerifiedIcon,
    UnverifiedIcon,
    NoverifyIcon,
    DataDirectoryIcon,
    LinkIcon,
    TrendIcon,
    CountIcon,
    FileIcon,
    HomeIcon,
    PipelineIcon,
    VersionIcon,
    LogIcon,
    RootIcon,
    GoIcon,
    ReleaseIcon,
    Icon,
    PreprocessIcon,
    ExtractIcon,
    DiffIcon,
    EvaluateIcon,
    ReportIcon,
    BatchIcon,
    BatchIndexIcon,
    CodeIcon,
}