build:
  dist: ./dist
  host: netlify
server:
  auth: ''
  dynamicTimeout: 60.0
  port: 3649
  readonly: false
site:
  description: 'A tool to detect API breaking changes in Python packages.'
  subtitle: 'Api EXplorer in PYthon.'
  title: 'AexPy'
